#theme: jekyll-theme-cayman
name: DaErich
title: DaErichs Software Lab
description: Where the magic happens
avatar: https://avatars2.githubusercontent.com/u/13851171?s=460&v=4
baseurl: "" 
plugins:
  - jemoji
footer-links:
  dribbble:
  email: daerich@users.sourceforge.net
  twitter: itsdaerich
  facebook:
  flickr:
  github: daerich
  youtube: /channel/UCrcbxvR_fQcaOWgrsIR8GTg
  steam: daerich

sass:
  style: :compressed

exclude: 
  - LICENSE
  - README.md
  - CNAME
  - trash
  - tutorial.md
