#theme: jekyll-theme-cayman
name: DaErichs Software Lab
title: DaErichs Software Lab
description: Where the magic happens
baseurl: "" 
plugins:
  - jemoji
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: daerich
